### ISSUE TITLE
Behavior of active tab of browser

### ISSUE THREAD

**Issue by haegemon** [haegemon/sync-tabs-functions#1]
If current tab active at User it should have more priority than blur tab

**Comment by craigjbass** [comment]
I wrote a proprietary library to do this. Really interesting to see something like this in the wild open source.

you should investigate web workers if you find your ticks are not ticking at the right speed. All the major browsers steal cycles from all blur tabs

I must admit we were basically making all tabs use one tab to share a web socket due to domain connection limitations. For this the master tab had to send heartbeat ticks.

**Comment by craigjbass** [comment]
And the heartbeats had to be reliable or it caused flapping

**Comment by haegemon** [comment]
This behavior can be realize through priority mechanism
